<?php
declare(strict_types=1);
ini_set('display_errors','0');
ini_set('display_startup_errors','0');
error_reporting(E_ALL);
$input=json_decode(file_get_contents('php://input')?:'',true);
$type=is_array($input)?trim((string)($input['type']??'pixels')):'';
if(!in_array($type,['cart_abandonment','friction_analyzer','schema_validator','pixels'],true)){require __DIR__.'/scanner-secure.php';exit;}
require_once __DIR__.'/security/url-validator.php';
require_once __DIR__.'/security/safe-http.php';
require_once __DIR__.'/security/rate-limit.php';
header('Content-Type: application/json; charset=utf-8');
function compat_json(array $p,int $s=200):void{http_response_code($s);echo json_encode($p,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
if(($_SERVER['REQUEST_METHOD']??'')!=='POST')compat_json(['success'=>false,'message'=>'Invalid request method.'],405);
if((int)($_SERVER['CONTENT_LENGTH']??0)>32768)compat_json(['success'=>false,'message'=>'Request is too large.'],413);
if(!is_array($input))compat_json(['success'=>false,'message'=>'Invalid JSON request.'],400);
if(!jt_rate_limit('scanner-compat',10,300))compat_json(['success'=>false,'message'=>'Too many scan requests. Please try again later.'],429);
function compat_html(string $url):string{[$ok,$normalized]=jt_validate_external_url($url);if(!$ok)compat_json(['success'=>false,'message'=>$normalized],422);$r=jt_safe_http_get($normalized,['timeout'=>12,'connect_timeout'=>5,'max_bytes'=>2097152,'user_agent'=>'JunctionTools-SecureScanner/1.0 (+https://junctiontools.com)']);if(!$r['success'])compat_json(['success'=>false,'message'=>$r['message']?:'Unable to fetch the target URL.'],422);return(string)$r['body'];}
switch($type){
case'cart_abandonment':$c=filter_var($input['total_carts']??null,FILTER_VALIDATE_INT);$o=filter_var($input['completed_orders']??null,FILTER_VALIDATE_INT);$a=filter_var($input['aov']??null,FILTER_VALIDATE_FLOAT);if($c===false||$o===false||$a===false||$c<=0||$o<0||$o>$c||$a<0)compat_json(['success'=>false,'message'=>'Please provide valid numbers for carts and orders.'],400);$ab=$c-$o;$rate=$ab/$c*100;$lost=$ab*$a;compat_json(['success'=>true,'abandonmentRate'=>$rate,'lostRevenue'=>$lost,'message'=>'Cart Abandonment Rate: <strong>'.number_format($rate,2).'%</strong><br>Abandoned Carts: <strong>'.$ab.'</strong><br>Estimated Lost Revenue: <strong>$'.number_format($lost,2).'</strong>']);
case'friction_analyzer':$checkout=trim((string)($input['checkout_type']??'1step'));$fields=filter_var($input['required_fields']??0,FILTER_VALIDATE_INT);$guest=trim((string)($input['guest_option']??'enabled'));if($fields===false||$fields<0||$fields>100)compat_json(['success'=>false,'message'=>'Please provide a valid required field count.'],400);$score=100;$tips=[];if($fields>8){$score-=($fields-8)*5;$tips[]="Aapke mandatory fields ({$fields}) bohat zyada hain.";}else$tips[]='Zabardast! Mandatory fields 8 ya us se kam hain.';if($guest==='forced'){$score-=30;$tips[]='Guest checkout zaroor enable karein.';}else$tips[]='Guest checkout enabled hai.';if($checkout==='3step'){$score-=15;$tips[]='3-step checkout zyada friction paida karta hai.';}$score=max(10,min(100,$score));compat_json(['success'=>true,'score'=>$score,'message'=>'Checkout Friction Score: '.$score.'/100. '.implode(' ',$tips)]);
case'schema_validator':$payload=trim((string)($input['payload']??''));if($payload!==''&&!preg_match('/^https?:\/\//i',$payload)){if(strlen($payload)>100000)compat_json(['success'=>false,'message'=>'Schema payload is too large.'],413);$d=json_decode($payload,true);if(json_last_error()!==JSON_ERROR_NONE||!is_array($d))compat_json(['success'=>true,'score'=>25,'schemaType'=>'Unknown / Custom Schema','syntaxStatus'=>'JSON Syntax Error','message'=>'Malformed JSON syntax. Please check for missing quotes, commas, or brackets.']);$st=$d['@type']??'Product / Generic Object';$st=is_array($st)?implode(', ',$st):(string)$st;compat_json(['success'=>true,'score'=>90,'schemaType'=>$st,'syntaxStatus'=>'Valid JSON Syntax Checked','message'=>'Raw JSON-LD syntax is clean and structurally compliant with Google rich snippet standards.']);}$url=trim((string)($input['url']??''));if($url===''||strlen($url)>2048)compat_json(['success'=>false,'message'=>'Please provide a valid URL.'],400);$html=compat_html($url);libxml_use_internal_errors(true);$dom=new DOMDocument();@$dom->loadHTML($html,LIBXML_NOERROR|LIBXML_NOWARNING|LIBXML_NONET);libxml_clear_errors();$xp=new DOMXPath($dom);$scripts=$xp->query('//script[@type="application/ld+json"]');if($scripts->length===0)compat_json(['success'=>true,'score'=>30,'schemaType'=>'Unknown / Custom Schema','syntaxStatus'=>'No JSON-LD Tag Found','message'=>'The target URL does not contain application/ld+json schema markup.']);$d=json_decode(trim($scripts->item(0)->nodeValue),true);if(json_last_error()!==JSON_ERROR_NONE)compat_json(['success'=>true,'score'=>40,'schemaType'=>'Unknown / Custom Schema','syntaxStatus'=>'Invalid JSON Syntax inside script tag','message'=>'Found JSON-LD script tag, but parsing failed due to syntax errors.']);$st=$d['@type']??'Product/Generic';$st=is_array($st)?implode(', ',$st):(string)$st;compat_json(['success'=>true,'score'=>95,'schemaType'=>$st,'syntaxStatus'=>'Valid JSON-LD Found in HTML','message'=>'Successfully extracted and validated JSON-LD schema from live URL.']);
case'pixels':$url=trim((string)($input['url']??''));if($url===''||strlen($url)>2048)compat_json(['success'=>false,'message'=>'Please provide a valid URL.'],400);$html=compat_html($url);$pixels=[];if(strpos($html,'connect.facebook.net')!==false||strpos($html,'fbq(')!==false)$pixels[]=['name'=>'Meta Pixel (Facebook/Instagram)','status'=>'Active','id'=>'Detected'];if(strpos($html,'analytics.tiktok.com')!==false||strpos($html,'ttq.load')!==false)$pixels[]=['name'=>'TikTok Pixel','status'=>'Active','id'=>'Detected'];if(strpos($html,'googletagmanager.com/gtag/js')!==false||strpos($html,'gtag(')!==false)$pixels[]=['name'=>'Google Tag (GA4 / Google Ads)','status'=>'Active','id'=>'Detected'];if(strpos($html,'pinit.js')!==false||strpos($html,'pinterest.com')!==false)$pixels[]=['name'=>'Pinterest Tag','status'=>'Active','id'=>'Detected'];compat_json(['success'=>true,'url'=>$url,'pixels_found'=>count($pixels),'pixels'=>$pixels]);
}